import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormField, Loader } from '../assets/components'

const CreatePost = () => {
  const navigate = useNavigate()
  const [form, setForm] = useState({ name: '', prompt: '', photo: '' })
  const [generatingImg, setGeneratingImg] = useState(false)
  const [loading, setLoading] = useState(false)

  return (
    <section className="max-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222238">Create</h1>
        <p className="mt-2 text-[16px] max-w[500px]">
          Create imatinative and visually stunning images generated by DALL-E AI
          and share them with the community
        </p>
      </div>
    </section>
  )
}

export default CreatePost
